theme: jekyll-theme-minimal
title: Dominik's Homepage
description: Bookmark this to keep an eye on my project updates!
lsi: false
safe: true
source: readme.md
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge